version: '3.8'
services:
  app:
    image: netris_solution
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - NODE_ENV=dev
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.18
    volumes:
      - ./app:/app/
    stdin_open: true
    tty: true
