version: '3.8'
services:
  app:
    image: netris_solution
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./app:/app/
    stdin_open: true
    tty: true
